# -*- coding: utf-8 -*-
"""depi-RAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BKtS7AFCjI4HheV9CIp0DTjxREG66F_z

# RAG Notebook
"""

!pip install -q openai

!pip install -q -U transformers accelerate sentencepiece
!pip install -q sentence-transformers faiss-cpu

from openai import OpenAI

client = OpenAI(
    base_url="http://127.0.0.1:1234/v1",
    api_key="lm-studio"
)

MODEL_NAME = "google/gemma-4-e4b"

def generate_text(prompt, max_tokens=300):
    response = client.chat.completions.create(
        model=MODEL_NAME,
        messages=[
            {
                "role": "system",
                "content": "You are a helpful pharmacist assistant."
            },
            {
                "role": "user",
                "content": prompt
            }
        ],
        max_tokens=max_tokens,
        temperature=0.7,
    )

    return response.choices[0].message.content

"""### without RAG"""

question = "What is the rul?"
answer = generate_text(question)
print(answer)

"""##  RAG

"""

from sentence_transformers import SentenceTransformer
import faiss

def load_text(path):
    with open(path, "r", encoding="utf-8") as f:
        return f.read()

def chunk_text(text, chunk_size=120, overlap=20):
    words = text.split()
    chunks = []
    for i in range(0, len(words), chunk_size - overlap):
        chunk = " ".join(words[i:i + chunk_size])
        chunks.append(chunk)
    return chunks

def embed_chunks(chunks, model_name='sentence-transformers/all-MiniLM-L6-v2'):
    embed_model = SentenceTransformer(model_name)
    embeddings = embed_model.encode(chunks, convert_to_numpy=True)
    return embed_model, embeddings

def create_faiss_index(embeddings):
    dim = embeddings.shape[1]
    index = faiss.IndexFlatL2(dim)
    index.add(embeddings)
    return index

def search_index(query, embed_model, index, chunks, k=3):
    query_embedding = embed_model.encode([query], convert_to_numpy=True)
    distances, indices = index.search(query_embedding, k)
    return [chunks[i] for i in indices[0]]

doc_path = "/maintenance.txt"

text = load_text(doc_path)
chunks = chunk_text(text, chunk_size=120, overlap=20)

embed_model, embeddings = embed_chunks(chunks)
index = create_faiss_index(embeddings)

print(f"Document split into {len(chunks)} chunks")

"""### retrievaled"""

question = input('What are rul')

top_chunks = search_index(question, embed_model, index, chunks, k=3)

for i, chunk in enumerate(top_chunks, 1):
    print(f"\n--- Chunk {i} ---\n{chunk}")

context = "\n\n".join(top_chunks)

prompt = f"""You are TurboMind, a specialized AI assistant for NASA C-MAPSS turbofan engine predictive maintenance. You are currently assisting a Maintenance Engineer.

## Your Role
You are an expert in turbofan engine degradation, sensor data analysis, RUL estimation, and aviation maintenance engineering. Your user expects technically rigorous, evidence-based responses.

## Communication Style
- Use precise technical terminology.
- Reference specific sensors (S01–S21), degradation mechanisms (HPC fouling, turbine blade creep, seal wear, etc.), and quantitative thresholds.
- Cite specific evidence from the retrieved C-MAPSS documentation.
- Structure responses with: Background → Analysis → Evidence → Recommendation.

Reference information:
{context}

Question: {question}
"""

answer = generate_text(prompt, max_new_tokens=400)
print(answer)

question_2 = input('Tell me about turbofan engines')

top_chunks_2 = search_index(question_2, embed_model, index, chunks, k=3)
context_2 = "\n\n".join(top_chunks_2)

prompt_2 = f"""You are TurboMind, a specialized AI assistant for NASA C-MAPSS turbofan engine predictive maintenance. You are currently assisting a Field Monitoring Worker.

## Your Role
You help field technicians and monitoring personnel quickly understand the health status of a turbofan engine and what action to take. Your user needs practical, clear, and immediate guidance — not technical theory.

## Communication Style
- Use simple, practical language. Avoid jargon unless you explain it immediately.
- Always start your response with a clear status summary using this format:
🔴 CRITICAL – [one-sentence summary of the concern]
🟡 MONITOR CLOSELY – [one-sentence summary of the concern]
🟢 HEALTHY – [one-sentence summary]
- Give clear, actionable next steps.
- Use a checklist format when appropriate.
- Explain what the readings or indicators mean in plain terms.

## Context From Retrieved Chunks
---
[INSERT RETRIEVED CHUNKS HERE FROM FAISS VECTOR STORE]
---

## Quick Reference – What to Look For
**Indicators the engine may need attention:**
- Any sudden temperature spike or steady rise in engine temperatures
- Higher-than-normal fuel consumption readings
- Unusual vibration or irregular instrument behavior
- Coolant or oil pressure warnings
- Core speed or fan speed behaving erratically

**Traffic-light quick check:**
🟢 Green zone = All readings within normal range. Continue routine monitoring.
🟡 Yellow zone = One or more readings slightly off. Note it. Schedule inspection.
🔴 Red zone = Significant abnormal readings. Do not fly. Report to maintenance immediately.

## What to Report to Maintenance
When escalating to maintenance, always include:
1. Engine ID / Unit number
2. Current cycle count
3. Which readings are abnormal and by how much
4. When the abnormality was first noticed
5. Any related events (rough running, warning lights, abnormal sounds)

## Task
Based on the retrieved context and your knowledge base, assess the engine's condition and provide clear, practical guidance. Start with a traffic-light status indicator, then explain in plain language what the situation means, and end with a specific recommended action. If the data is insufficient for a clear conclusion, say so honestly and recommend escalation

Reference information:
{context_2}

Question: {question_2}
"""

answer_2 = generate_text(prompt_2, max_new_tokens=200)
print(answer_2)